### ISSUE TITLE
The video is functioning correctly, but there is an issue with the audio.

### ISSUE THREAD

**Issue by vlingo8888** [react-native-webrtc/react-native-webrtc-web-shim#9]
Hi, I encountered an issue while creating a group video call. The video is functioning as expected, but unfortunately, there seems to be a problem with the audio. Below is the code I've implemented. Can you spot any mistakes?

```javascript
export function MultipleWebRTCVoiceChat() {
  const navigation = useNavigation();
  let peerConnections = React.useRef<Record<string, RTCPeerConnection | null>>(
    {}
  ).current;
  const [localStream, setLocalStream, getLocalStream] =
    useAdvancedState<MediaStream | null>(null);
  const [remoteStreams, setRemoteStreams] = React.useState<
    Record<string, MediaStream>
  >({});
  const [socket, setSocket, getSocket] = useAdvancedState<any>(null);
  const mySocketId = React.useRef<string>("");

  const localStreamRef = React.useRef<MediaStream | null>(null);

  const [room, setRoom] = React.useState<string>("123");
  const [isMuted, setIsMuted] = React.useState<boolean>(false);
  const [isCamera, setIsCamera] = React.useState<boolean>(true);
  const [isConnected, setIsConnected] = React.useState<boolean>(false);
  const [isJoined, setIsJoined] = React.useState<boolean>(false);
  const [isConnectError, setIsConnectError] = React.useState<boolean>(false);

  const getPeerConnection = async (socketId: string) => {
    if (peerConnections[socketId]) {
      return peerConnections[socketId];
    }
    const localStream = getLocalStream();
    const configuration = {
      iceServers: [
        {
          urls: "stun:stun.l.google.com:19302",
        },
        {
          urls: "stun:stun1.l.google.com:19302",
        },
      ],
    };
    const pc = new RTCPeerConnection(configuration);

    // localStream?.getAudioTracks().forEach((track: any) => {
    //     pc.addTrack(track, localStream as any);
    // });

    // localStream?.getVideoTracks().forEach((track: any) => {
    //     pc.addTrack(track, localStream as any);
    // });

    localStream?.getTracks().forEach((track: any) => {
      pc.addTrack(track, localStream as any);
    });

    pc.onsignalingstatechange = (event: any) => {
      console.log("onsignalingstatechange", event);
    };

    pc.onaddstream = (event: any) => {
      console.log("onaddstream", event);
      setRemoteStreams((old) => ({
        ...old,
        [socketId]: event.stream,
      }));
    };

    pc.onicecandidate = (event: any) => {
      const socket = getSocket();
      if (event.candidate) {
        socket.emit("ice-candidate", {
          room: room,
          candidate: event.candidate,
        });
      }
    };

    pc.ontrack = (event: any) => {
      if (mySocketId.current !== socketId) {
        console.log("ontrack", mySocketId.current, socketId, event.track.kind);
      }
      setRemoteStreams((old) => ({
        ...old,
        [socketId]: event.streams[0],
      }));
    };

    peerConnections[socketId] = pc;

    return pc;
  };

  const init = async () => {
    localStreamRef.current = await mediaDevices.getUserMedia({
      audio: true,
      video: isCamera,
    });

    setLocalStream(localStreamRef.current as any);
    const socket = io(SOCKET_STREAM_URL, {
      transports: ["websocket"],
    });
    socket.on("connect_error", async (err: any) => {
      console.log("connect_error", err, err.message);
      setIsConnectError(true);
      setIsConnected(false);
      setIsJoined(false);
    });
    socket.on("connect", () => {
      setIsConnectError(false);
      setIsConnected(true);
      const socketId = socket.id;
      setSocket(socket);
      mySocketId.current = socketId;
      handleJoinRoom();
    });

    socket.on("offer", handleOffer);
    socket.on("answer", handleAnswer);
    socket.on("ice-candidate", handleIceCandidate);
    socket.on("user-connected", handleUserConnected);
    socket.on("user-disconnected", handleUserDisconnected);
  };

  const handleUserConnected = async (socketId: string) => {
    console.log("handleUserConnected", socketId);
    const socket = getSocket();
    const pc = await getPeerConnection(socketId);
    const offer = await pc.createOffer({
      offerToReceiveAudio: true,
      offerToReceiveVideo: true,
    });
    await pc.setLocalDescription(new RTCSessionDescription(offer));
    socket.emit("offer", {
      target: socketId,
      offer: offer,
    });
  };

  const handleUserDisconnected = (socketId: string) => {
    peerConnections[socketId]?.close();
    peerConnections[socketId] = null;
    setRemoteStreams((old) => {
      delete old[socketId];
      return old;
    });
  };

  const handleOffer = async (event: { source: string; offer: any }) => {
    const { source, offer } = event;
    console.log("handleOffer", event);
    const socket = getSocket();
    const pc = await getPeerConnection(source);
    await pc.setRemoteDescription(new RTCSessionDescription(offer));
    const answer = await pc.createAnswer();
    await pc.setLocalDescription(new RTCSessionDescription(answer));
    socket.emit("answer", {
      target: source,
      answer: answer,
    });
  };

  const handleAnswer = async (payload: { source: string; answer: any }) => {
    console.log("handleAnswer", payload);
    const { source, answer } = payload;
    const pc = await getPeerConnection(source);
    await pc.setRemoteDescription(new RTCSessionDescription(answer));
  };

  const handleIceCandidate = async (event: {
    source: string;
    candidate: any;
  }) => {
    console.log("handleIceCandidate", event);
    const { source, candidate } = event;
    const pc = await getPeerConnection(source);
    if (!pc) {
      return;
    }
    await pc.addIceCandidate(new RTCIceCandidate(candidate));
  };

  useEffect(() => {
    init();
  }, []);

  const handleJoinRoom = async () => {
    const socket = getSocket();
    socket.emit("join-room", room);
    setIsJoined(true);
  };

  const handleLeaveRoom = () => {
    const socket = getSocket();
    socket.emit("leave-room", room);
    setIsJoined(false);
  };

  const handleShareScreen = async () => {
    const stream = await mediaDevices.getDisplayMedia({
      audio: true,
      video: true,
    });
    setLocalStream(stream as any);
    stream.getTracks().forEach((track: any) => {
      peerConnections[room]?.addTrack(track, stream);
    });
  };

  const handleShareCamera = async () => {
    localStream?.getVideoTracks().forEach((track: any) => {
      track.enabled = true;
    });
  };

  const handleShareCameraOff = async () => {
    localStream?.getVideoTracks().forEach((track: any) => {
      track.enabled = false;
    });
  };

  const handleShareAudio = async () => {
    const stream = await mediaDevices.getUserMedia({
      audio: true,
      video: false,
    });
    setLocalStream(stream as any);
    stream.getTracks().forEach((track: any) => {
      peerConnections[room]?.addTrack(track, stream);
    });
  };

  const handleMute = () => {
    const localStream = getLocalStream();
    localStream?.getAudioTracks().forEach((track: any) => {
      track.enabled = !track.enabled;
    });
    setIsMuted(true);
  };

  const handleUnmute = () => {
    const localStream = getLocalStream();
    localStream?.getAudioTracks().forEach((track: any) => {
      track.enabled = !track.enabled;
    });
    setIsMuted(false);
  };

  useEffect(() => {
    if (isMuted) {
      handleMute();
    } else {
      handleUnmute();
    }
  }, [isMuted]);

  useEffect(() => {
    if (isCamera) {
      handleShareCamera();
    } else {
      handleShareCameraOff();
    }
  }, [isCamera]);

  console.log("remoteStreams", remoteStreams);

  if (isConnectError) {
    return (
      <View
        style={{
          backgroundColor: "transparent",
          flex: 1,
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Text
          style={{
            color: "white",
            fontSize: 20,
            textAlign: "center",
          }}
        >
          Cannot connect to video call
        </Text>
      </View>
    );
  }

  return (
    <View
      style={{
        backgroundColor: "transparent",
      }}
    >
      {isConnected ? (
        <View
          style={{
            backgroundColor: "transparent",
          }}
        >
          <View
            style={{
              flexDirection: "row",
              flexWrap: "wrap",
              backgroundColor: "transparent",
              padding: 16,
            }}
          >
            <StreamMedia
              isMuted={isMuted}
              fullName="You"
              isVideoOff={!isCamera}
              stream={localStream}
            />

            {Object.keys(remoteStreams).map((id) => (
              <StreamMedia stream={remoteStreams[id]} />
            ))}
          </View>
        </View>
      ) : (
        <View></View>
      )}

      <Row
        style={{
          marginLeft: 26,
        }}
      >
        <Col>
          <SwitchButton
            value={isMuted}
            onChange={setIsMuted}
            views={[
              {
                value: false,
                view: <Octicons name="unmute" size={14} color="gray" />,
              },
              {
                value: true,
                view: <Octicons name="mute" size={14} color="gray" />,
              },
            ]}
          />
        </Col>

        <Col
          style={{
            marginLeft: 6,
          }}
        >
          <SwitchButton
            value={isCamera}
            onChange={setIsCamera}
            views={[
              {
                value: false,
                view: <Feather name="video-off" size={14} color="gray" />,
              },
              {
                value: true,
                view: <Feather name="video" size={14} color="gray" />,
              },
            ]}
          />
        </Col>

        {isConnected && (
          <Col
            style={{
              marginLeft: 6,
            }}
          >
            <SwitchButton
              value={isJoined}
              onChange={!isJoined ? handleJoinRoom : handleLeaveRoom}
              views={[
                {
                  value: false,
                  view: <Text>Join</Text>,
                },
                {
                  value: true,
                  view: <Text>End Calling</Text>,
                },
              ]}
            />
          </Col>
        )}
      </Row>
    </View>
  );
}

```

**Comment by 8BallBomBom** [comment]
I'm not seeing anything too obvious other than some code i can't investigate as it isn't included 🤔 

Can you provide more info?
Which platform are you having issues with?
and have you tested other platforms?

**Comment by vlingo8888** [comment]
Hi @8BallBomBom Thanks you. I haven't test other platforms yet but only web. Now, i know where is problem: RTCView from "react-native-webrtc-web-shim" seems to not work with audio. So i try with custom player, then it work perfectly:

**Comment by 8BallBomBom** [comment]
Ahhhh interesting find and thanks for debugging 😸 
There is a module rewrite planned in the near future so we will have to address this issue 👍🏻

**Comment by MehmetKaplan** [comment]
Hi @8BallBomBom ,

This is exactly what we are stuck also. The Video Call starts by default muted and whatever we do, we can not programmatically override the flag. 

What we did is:

```
if (remoteStream) {
	for (let i = 0; i < remoteStream.getTracks().length; i++) {
		if (remoteStream.getTracks()[i].kind === "audio") {
			remoteStream.getTracks()[i].enabled = true;
		}
	}
}
```

Is there any workaround that we can do until that bug fix? (Or even better, is there a planned fix date?)

**Comment by 8BallBomBom** [comment]
Been a bit busy but I'll be looking to test and push out a fix over the next week 😀

**Comment by MehmetKaplan** [comment]
Hi @8BallBomBom ,

Would you please let me know the steps to test? (I believe cloning the repo and replacing what lies under the node_modules should not be sufficient. :-/

**Comment by 8BallBomBom** [comment]
Ahhh, no worries 😸 
You should be able to test the new branch by executing one of the following commands in your project directory.
Just depends on which package manager you use.
```
npm install react-native-webrtc/react-native-webrtc-web-shim/#1.0.6 --save
yarn add react-native-webrtc/react-native-webrtc-web-shim/#1.0.6
pnpm install react-native-webrtc/react-native-webrtc-web-shim/#1.0.6
```

**Comment by MehmetKaplan** [comment]
Thanks @8BallBomBom 

Here are my 2 findings (first is the important one):


1. I got following error:

  ```
  RTCPeerConnection is not a constructor
  ```
  Digging the problem, I suspect from the `index.js` file which does not export the same objects.

  **v1.0.6**
  ```javascript
  import {
    MediaStream,
    MediaStreamTrack,
    RTCView,
  } from './src/react-native-webrtc-web-shim';

  export { MediaStream, MediaStreamTrack, RTCView };
  ```
  **v1.0.5**
  ```javascript
  import {
    MediaStream,
    MediaStreamTrack,
    RTCView,
  } from './src/react-native-webrtc-web-shim';

  export { MediaStream, MediaStreamTrack, RTCView };
  ```

2. Necessity of node 18. I think previous version did not dictate the node version to be 18.

  ```
  $ yarn add 'react-native-webrtc-web-shim@https://github.com/react-native-webrtc/react-native-webrtc-web-shim#1.0.6'
  yarn add v1.22.19
  ...
  [2/4] 🚚  Fetching packages...
  error lint-staged@15.2.0: The engine "node" is incompatible with this module. Expected version ">=18.12.0". Got "16.20.0"
  error Found incompatible module.
  ...
  ```

________________

To be specific I used this command to install:

  ```shell
  yarn add 'react-native-webrtc-web-shim@https://github.com/react-native-webrtc/react-native-webrtc-web-shim#1.0.6'
  ```

**Comment by 8BallBomBom** [comment]
Figured it wasn't necessary to import and export objects from another module that wasn't actually being altered.
So them changes will be mentioned in the upcoming update.
If that becomes an issue then we can revert the changes.

As for the node issue, that is likely caused by dependency updates.
We don't currently specify the node version in the `package.json` file.
But also newer versions of React Native are now using node 18.

**Comment by MehmetKaplan** [comment]
Sorry, I could not get this part:

> Figured it wasn't necessary to import and export objects from another module that wasn't actually being altered.

The previously exported objects will be exported in the new version so that we can use them, right? :-)

**Comment by 8BallBomBom** [comment]
You should be able to use the other objects directly from `react-native-webrtc`.
But the following should be imported from this module instead.
`MediaStream`, `MediaStreamTrack`, `RTCView`

Seemed strange to import and then instantly export objects from the other module.
If we actually imported them to then export altered versions then it would make sense.
But we weren't doing that as such.
Hope that makes sense 😉

As always the issue is up for debate, hopefully not caused too much disruption.
Question is, everything now working as expected?

**Comment by MehmetKaplan** [comment]
First of all, I understand the rationale and I am ok to import the remaining objects directly from `react-native-webrtc`.

That said, the method in v1.0.5 was enabling us to import `react-native-webrtc-web-shim` as if it was a "drop-in" replacement of `react-native-webrtc` for the web.

What I mean is, I had below 2 files:

```javascript
// webrtc/react-native-webrtc.js
export * from "react-native-webrtc-web-shim";
```

```javascript
// webrtc/react-native-webrtc.native.js
export * from "react-native-webrtc";
```

And when using simply importing with a single method:

```javascript
import {
	mediaDevices,
	RTCPeerConnection,
	RTCSessionDescription,
	RTCView,
	...
} from "./webrtc/react-native-webrtc";

```
By this way, we can utilize React Native's build behavior, so that web builds go to the `react-native-webrtc-web-shim` and native builds go to the `react-native-webrtc`. Of course this still can be achieved but from the users' perspective, the method in v1.0.5 requires -slightly- less coding.

At the end of the day you are the boss. :-) But I would kindly suggest keeping the API not impacted.

**Comment by MehmetKaplan** [comment]
One more information. Apparently I lack the information about how to;
> ... be able to use the other objects directly from react-native-webrtc

What I do:
```javascript
// webrtc/react-native-webrtc.js
import {
	RTCPeerConnection,
	RTCIceCandidate,
	RTCSessionDescription,
	mediaDevices,
	permissions,
	registerGlobals,
 } from "react-native-webrtc";
 
 import {
	MediaStream,
	MediaStreamTrack,
	RTCView,
 } from "react-native-webrtc-web-shim";
 
 export {
	RTCPeerConnection,
	RTCIceCandidate,
	RTCSessionDescription,
	MediaStream,
	MediaStreamTrack,
	mediaDevices,
	permissions,
	registerGlobals,
	RTCView
 };
```

Then I get the following error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-native-web/dist/exports/PermissionsAndroid' in '/Users/mehmetkaplan/ActiveCodes/ayebuy/ayebuy-webrtc-example-frontend/node_modules/react-native-webrtc/lib/module'
```

**Comment by 8BallBomBom** [comment]
Generally speaking you shouldn't need to import the `permissions` object as permissions are handled during runtime when the camera and microphone is requested. That being said it is usually best to ensure the permissions are granted way before that point.

As for the whole API changes with importing and exporting, you have a bit of a different point of view than i do but i can understand wanting to just import everything from one place rather than multiple places 🤔 
I will revise that decision and look at adding the newer API functionality aswell.

I also removed the use of `memo` on the `RTCView` as it didn't seem necessary.
Will run some tests to ensure things are working as expected then push another update later today 👍🏻

**Comment by 8BallBomBom** [comment]
Will be looking to release an update soon if there's no other issues 😅

**Comment by MehmetKaplan** [comment]
Hi @8BallBomBom ,

First my apologies for late response again. :-S

I am not sure if I did something wrong (I just install the package and built the code without changing anything) but I got the following error:

```python
react-dom.production.min.js:189 TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at nonIterableSpread.js:2:9
    at i (toConsumableArray.js:6:95)
    at p (RTCView.web.js:23:26)
    at Ca (react-dom.production.min.js:167:137)
    at Cs (react-dom.production.min.js:290:337)
    at wu (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at mu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at uu (react-dom.production.min.js:273:300)
```

The steps to produce:

1. Install the package as the previous method:
```shell
yarn add 'react-native-webrtc-web-shim@https://github.com/react-native-webrtc/react-native-webrtc-web-shim#1.0.6'
```
2. Expo build and deploy to be served statically:
```
npx expo export:web
...
pm2 start ecosystem.config.js --env=test;
```

**Comment by 8BallBomBom** [comment]
No worries, it is end of year and holiday season after all 😀 

Wasn't experiencing any issues when testing but was not using expo 🤔 will push out another patch shortly 👍

**Comment by MehmetKaplan** [comment]
Superb, works like charm. 💯✅👍

Thanks a lot @8BallBomBom

**Comment by 8BallBomBom** [comment]
Great to hear, thanks for the help, will push the update out 😸 
Happy Holidays 🎄
